{% set name = "Orange3-Educational" %}
{% set version = "0.1.8" %}
{% set sha256 = "bac780e923788580e156fe49b23e7f68b98a81861158ce9302138957bbffe9ba" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .
  preserve_egg_dir: True

requirements:
  build:
    - python
    - pip
    - setuptools
  run:
    - python
    - orange3

test:
  imports:
    - orangecontrib.educational

about:
  home: https://github.com/biolab/orange3-educational
  license: CC-BY-NC-3.0
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'Educational widgets for machine learning and data mining in Orange 3.'

  description: |
    Widgets in Educational Add-on demonstrate several key data mining and machine
    learning procedures. The widgets are useful for beginners to understand the
    inner working of key algorithms in the data mining and for teachers to be
    able to visually explain various methods in a classroom.
  doc_url: http://orange3-educational.readthedocs.io/
  dev_url: https://github.com/biolab/orange3-educational

extra:
  recipe-maintainers:
    - primozgodec
